#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% IMPORTS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
from PyQt4 import QtCore, QtGui
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Motorlab(object):
    def setupUi(self, Motorlab):
        Motorlab.setObjectName(_fromUtf8("Motorlab"))
        Motorlab.setFixedSize(1004, 580)
        Motorlab.setAutoFillBackground(False)
        Motorlab.setDocumentMode(False)
        
        import sys
        if getattr(sys, 'frozen', None):
            
            basedir = sys._MEIPASS
            
        else:
            
            import os
            
            basedir = os.path.dirname(__file__)
		
        # Create and display the splash screen
        directory_to_image = str(basedir) + '\Data\motorlabicon.png'
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(directory_to_image)), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Motorlab.setWindowIcon(icon)
		
        self.centralWidget = QtGui.QWidget(Motorlab)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
         
        self.ControllerGroup = QtGui.QGroupBox(self.centralWidget)
        self.ControllerGroup.setGeometry(QtCore.QRect(10, 320, 251, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.ControllerGroup.setFont(font)
        self.ControllerGroup.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ControllerGroup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ControllerGroup.setAutoFillBackground(False)
        self.ControllerGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.ControllerGroup.setObjectName(_fromUtf8("ControllerGroup"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.ControllerGroup)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 231, 101))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.ParametersLayout = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.ParametersLayout.setMargin(11)
        self.ParametersLayout.setSpacing(6)
        self.ParametersLayout.setObjectName(_fromUtf8("ParametersLayout"))
        self.KdLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.KdLabel.setFont(font)
        self.KdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.KdLabel.setObjectName(_fromUtf8("KdLabel"))
        self.ParametersLayout.addWidget(self.KdLabel, 1, 0, 1, 1)
        self.KiLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.KiLabel.setFont(font)
        self.KiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.KiLabel.setObjectName(_fromUtf8("KiLabel"))
        self.ParametersLayout.addWidget(self.KiLabel, 2, 0, 1, 1)
        self.Kd = QtGui.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Kd.setFont(font)
        self.Kd.setAlignment(QtCore.Qt.AlignCenter)
        self.Kd.setObjectName(_fromUtf8("Kd"))
        self.ParametersLayout.addWidget(self.Kd, 1, 1, 1, 1)
        self.Ki = QtGui.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Ki.setFont(font)
        self.Ki.setAlignment(QtCore.Qt.AlignCenter)
        self.Ki.setObjectName(_fromUtf8("Ki"))
        self.ParametersLayout.addWidget(self.Ki, 2, 1, 1, 1)
        self.Kp = QtGui.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Kp.setFont(font)
        self.Kp.setAlignment(QtCore.Qt.AlignCenter)
        self.Kp.setObjectName(_fromUtf8("Kp"))
        self.ParametersLayout.addWidget(self.Kp, 0, 1, 1, 1)
        self.KpLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KpLabel.sizePolicy().hasHeightForWidth())
        self.KpLabel.setSizePolicy(sizePolicy)
        self.KpLabel.setMinimumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.KpLabel.setFont(font)
        self.KpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.KpLabel.setObjectName(_fromUtf8("KpLabel"))
        self.ParametersLayout.addWidget(self.KpLabel, 0, 0, 1, 1)
        self.OLRadioButton = QtGui.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.OLRadioButton.setFont(font)
        self.OLRadioButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OLRadioButton.setChecked(True)
        self.OLRadioButton.setObjectName(_fromUtf8("OLRadioButton"))
        self.ParametersLayout.addWidget(self.OLRadioButton, 0, 2, 1, 1)
        self.PosConRadioButton = QtGui.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.PosConRadioButton.setFont(font)
        self.PosConRadioButton.setObjectName(_fromUtf8("PosConRadioButton"))
        self.ParametersLayout.addWidget(self.PosConRadioButton, 1, 2, 1, 1)
        self.SpeedConRadioButton = QtGui.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.SpeedConRadioButton.setFont(font)
        self.SpeedConRadioButton.setObjectName(_fromUtf8("SpeedConRadioButton"))
        self.ParametersLayout.addWidget(self.SpeedConRadioButton, 2, 2, 1, 1)
        self.DataCollectionGroup = QtGui.QGroupBox(self.centralWidget)
        self.DataCollectionGroup.setGeometry(QtCore.QRect(10, 10, 251, 301))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.DataCollectionGroup.setFont(font)
        self.DataCollectionGroup.setAcceptDrops(False)
        self.DataCollectionGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.DataCollectionGroup.setFlat(False)
        self.DataCollectionGroup.setCheckable(False)
        self.DataCollectionGroup.setObjectName(_fromUtf8("DataCollectionGroup"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.DataCollectionGroup)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 231, 111))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.DataCollectionLayout = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.DataCollectionLayout.setMargin(11)
        self.DataCollectionLayout.setSpacing(6)
        self.DataCollectionLayout.setObjectName(_fromUtf8("DataCollectionLayout"))
        self.FileName = QtGui.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.FileName.setFont(font)
        self.FileName.setAlignment(QtCore.Qt.AlignCenter)
        self.FileName.setObjectName(_fromUtf8("FileName"))
        self.DataCollectionLayout.addWidget(self.FileName, 3, 1, 1, 1)
        self.SampleRateLabel = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.SampleRateLabel.setFont(font)
        self.SampleRateLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.SampleRateLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.SampleRateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SampleRateLabel.setObjectName(_fromUtf8("SampleRateLabel"))
        self.DataCollectionLayout.addWidget(self.SampleRateLabel, 0, 0, 1, 1)
        self.FileVariableNameLabel = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.FileVariableNameLabel.setFont(font)
        self.FileVariableNameLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.FileVariableNameLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.FileVariableNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FileVariableNameLabel.setObjectName(_fromUtf8("FileVariableNameLabel"))
        self.DataCollectionLayout.addWidget(self.FileVariableNameLabel, 3, 0, 1, 1)
        self.Duration = QtGui.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Duration.setFont(font)
        self.Duration.setAlignment(QtCore.Qt.AlignCenter)
        self.Duration.setObjectName(_fromUtf8("Duration"))
        self.DataCollectionLayout.addWidget(self.Duration, 2, 1, 1, 1)
        self.SampleCount = QtGui.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.SampleCount.setFont(font)
        self.SampleCount.setAlignment(QtCore.Qt.AlignCenter)
        self.SampleCount.setObjectName(_fromUtf8("SampleCount"))
        self.DataCollectionLayout.addWidget(self.SampleCount, 1, 1, 1, 1)
        self.SampleCountLabel = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.SampleCountLabel.setFont(font)
        self.SampleCountLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.SampleCountLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.SampleCountLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SampleCountLabel.setObjectName(_fromUtf8("SampleCountLabel"))
        self.DataCollectionLayout.addWidget(self.SampleCountLabel, 1, 0, 1, 1)
        self.DurationLabel = QtGui.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.DurationLabel.setFont(font)
        self.DurationLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.DurationLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.DurationLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DurationLabel.setObjectName(_fromUtf8("DurationLabel"))
        self.DataCollectionLayout.addWidget(self.DurationLabel, 2, 0, 1, 1)
        self.SampleRate = QtGui.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.SampleRate.setFont(font)
        self.SampleRate.setAlignment(QtCore.Qt.AlignCenter)
  
        self.SampleRate.setObjectName(_fromUtf8("SampleRate"))
        self.DataCollectionLayout.addWidget(self.SampleRate, 0, 1, 1, 1)
        self.DataButtonGroup = QtGui.QGroupBox(self.DataCollectionGroup)
        self.DataButtonGroup.setGeometry(QtCore.QRect(10, 140, 231, 151))
        self.DataButtonGroup.setTitle(_fromUtf8(""))
        self.DataButtonGroup.setObjectName(_fromUtf8("DataButtonGroup"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.DataButtonGroup)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 211, 131))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.DataButtonsLayout = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.DataButtonsLayout.setMargin(11)
        self.DataButtonsLayout.setSpacing(6)
        self.DataButtonsLayout.setObjectName(_fromUtf8("DataButtonsLayout"))
        self.OpenPython = QtGui.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.OpenPython.setFont(font)
        self.OpenPython.setObjectName(_fromUtf8("OpenPython"))
        self.DataButtonsLayout.addWidget(self.OpenPython, 3, 1, 1, 1)
        self.StartButton = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.StartButton.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.StartButton.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.StartButton.setFont(font)
        self.StartButton.setCheckable(True)
        self.StartButton.setChecked(False)
        self.StartButton.setAutoDefault(False)
        self.StartButton.setDefault(False)
        self.StartButton.setFlat(False)
        self.StartButton.setObjectName(_fromUtf8("StartButton"))
        self.DataButtonsLayout.addWidget(self.StartButton, 1, 0, 1, 2)
        self.CollectDataButton = QtGui.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.CollectDataButton.setFont(font)
        self.CollectDataButton.setCheckable(True)
        self.CollectDataButton.setObjectName(_fromUtf8("CollectDataButton"))
        self.DataButtonsLayout.addWidget(self.CollectDataButton, 3, 0, 1, 1)
        self.StopButton = QtGui.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.StopButton.setFont(font)
        self.StopButton.setObjectName(_fromUtf8("StopButton"))
        self.DataButtonsLayout.addWidget(self.StopButton, 2, 1, 1, 1)
        self.StartAndCollectButton = QtGui.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.StartAndCollectButton.setFont(font)
        self.StartAndCollectButton.setCheckable(True)
        self.StartAndCollectButton.setObjectName(_fromUtf8("StartAndCollectButton"))
        self.DataButtonsLayout.addWidget(self.StartAndCollectButton, 2, 0, 1, 1)
        self.OpenDirectoryButton = QtGui.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.OpenDirectoryButton.setFont(font)
        self.OpenDirectoryButton.setObjectName(_fromUtf8("OpenDirectoryButton"))
        self.DataButtonsLayout.addWidget(self.OpenDirectoryButton, 0, 0, 1, 1)
        self.GenerateFileButton = QtGui.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.GenerateFileButton.setFont(font)
        self.GenerateFileButton.setObjectName(_fromUtf8("GenerateFileButton"))
        self.DataButtonsLayout.addWidget(self.GenerateFileButton, 0, 1, 1, 1)
        self.DataExplorerGroup = QtGui.QGroupBox(self.centralWidget)
        self.DataExplorerGroup.setGeometry(QtCore.QRect(270, 10, 281, 311))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DataExplorerGroup.setFont(font)
        self.DataExplorerGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.DataExplorerGroup.setObjectName(_fromUtf8("DataExplorerGroup"))
        self.DataExplorer = QtGui.QTextBrowser(self.DataExplorerGroup)
        self.DataExplorer.setGeometry(QtCore.QRect(10, 20, 261, 281))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.DataExplorer.setFont(font)
        self.DataExplorer.setFrameShadow(QtGui.QFrame.Raised)
        self.DataExplorer.setObjectName(_fromUtf8("DataExplorer"))
        self.PlotToolsGroup = QtGui.QGroupBox(self.centralWidget)
        self.PlotToolsGroup.setGeometry(QtCore.QRect(560, 10, 231, 311))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PlotToolsGroup.setFont(font)
        self.PlotToolsGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.PlotToolsGroup.setObjectName(_fromUtf8("PlotToolsGroup"))
        self.DataPlotGroup = QtGui.QGroupBox(self.PlotToolsGroup)
        self.DataPlotGroup.setGeometry(QtCore.QRect(10, 20, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.DataPlotGroup.setFont(font)
        self.DataPlotGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.DataPlotGroup.setObjectName(_fromUtf8("DataPlotGroup"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.DataPlotGroup)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 191, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.PlotDataButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.PlotDataButton.setFont(font)
        self.PlotDataButton.setCheckable(False)
        self.PlotDataButton.setChecked(False)
        self.PlotDataButton.setDefault(False)
        self.PlotDataButton.setFlat(False)
        self.PlotDataButton.setObjectName(_fromUtf8("PlotDataButton"))
        self.horizontalLayout_2.addWidget(self.PlotDataButton)
        self.ModelPlotGroup = QtGui.QGroupBox(self.PlotToolsGroup)
        self.ModelPlotGroup.setGeometry(QtCore.QRect(10, 100, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ModelPlotGroup.setFont(font)
        self.ModelPlotGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.ModelPlotGroup.setObjectName(_fromUtf8("ModelPlotGroup"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.ModelPlotGroup)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 191, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.StepModelButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.StepModelButton.setFont(font)
        self.StepModelButton.setFlat(False)
        self.StepModelButton.setObjectName(_fromUtf8("StepModelButton"))
        self.horizontalLayout_3.addWidget(self.StepModelButton)
        self.BodeModelButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.BodeModelButton.setFont(font)
        self.BodeModelButton.setAutoFillBackground(False)
        self.BodeModelButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.BodeModelButton.setFlat(False)
        self.BodeModelButton.setObjectName(_fromUtf8("BodeModelButton"))
        self.horizontalLayout_3.addWidget(self.BodeModelButton)
        self.ComparisonGroup = QtGui.QGroupBox(self.PlotToolsGroup)
        self.ComparisonGroup.setGeometry(QtCore.QRect(10, 170, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ComparisonGroup.setFont(font)
        self.ComparisonGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.ComparisonGroup.setObjectName(_fromUtf8("ComparisonGroup"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.ComparisonGroup)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 191, 41))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.DataModelButton = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.DataModelButton.setFont(font)
        self.DataModelButton.setFlat(False)
        self.DataModelButton.setObjectName(_fromUtf8("DataModelButton"))
        self.horizontalLayout_4.addWidget(self.DataModelButton)
        self.gridLayoutWidget_5 = QtGui.QWidget(self.PlotToolsGroup)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 240, 191, 71))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.FitDataCheckBox = QtGui.QCheckBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.FitDataCheckBox.setFont(font)
        self.FitDataCheckBox.setObjectName(_fromUtf8("FitDataCheckBox"))
        self.gridLayout_2.addWidget(self.FitDataCheckBox, 1, 0, 1, 1)
        self.PlotAutoFormatCheckBox = QtGui.QCheckBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.PlotAutoFormatCheckBox.setFont(font)
        self.PlotAutoFormatCheckBox.setChecked(False)
        self.PlotAutoFormatCheckBox.setObjectName(_fromUtf8("PlotAutoFormatCheckBox"))
        self.gridLayout_2.addWidget(self.PlotAutoFormatCheckBox, 2, 0, 1, 1)
        self.PlotAllDataCheckBox = QtGui.QCheckBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.PlotAllDataCheckBox.setFont(font)
        self.PlotAllDataCheckBox.setObjectName(_fromUtf8("PlotAllDataCheckBox"))
        self.gridLayout_2.addWidget(self.PlotAllDataCheckBox, 1, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_2.addWidget(self.checkBox, 2, 1, 1, 1)
        self.ModelGroup = QtGui.QGroupBox(self.centralWidget)
        self.ModelGroup.setGeometry(QtCore.QRect(800, 10, 191, 181))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ModelGroup.setFont(font)
        self.ModelGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.ModelGroup.setObjectName(_fromUtf8("ModelGroup"))
        self.TransferFunctionGroup = QtGui.QGroupBox(self.ModelGroup)
        self.TransferFunctionGroup.setGeometry(QtCore.QRect(10, 20, 171, 141))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.TransferFunctionGroup.setFont(font)
        self.TransferFunctionGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.TransferFunctionGroup.setObjectName(_fromUtf8("TransferFunctionGroup"))
        self.gridLayoutWidget = QtGui.QWidget(self.TransferFunctionGroup)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 151, 111))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Numerator = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Numerator.setFont(font)
        self.Numerator.setAlignment(QtCore.Qt.AlignCenter)

        self.Numerator.setObjectName(_fromUtf8("Numerator"))
        self.gridLayout.addWidget(self.Numerator, 1, 0, 1, 1)
        self.Denominator = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Denominator.setFont(font)
        self.Denominator.setAlignment(QtCore.Qt.AlignCenter)
  
        self.Denominator.setObjectName(_fromUtf8("Denominator"))
        self.gridLayout.addWidget(self.Denominator, 3, 0, 1, 1)
        self.NumeratorLabel = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.NumeratorLabel.setFont(font)
        self.NumeratorLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NumeratorLabel.setAutoFillBackground(False)
        self.NumeratorLabel.setInputMethodHints(QtCore.Qt.ImhNone)
        self.NumeratorLabel.setFrameShape(QtGui.QFrame.Box)
        self.NumeratorLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.NumeratorLabel.setTextFormat(QtCore.Qt.AutoText)
        self.NumeratorLabel.setScaledContents(False)
        self.NumeratorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NumeratorLabel.setObjectName(_fromUtf8("NumeratorLabel"))
        self.gridLayout.addWidget(self.NumeratorLabel, 0, 0, 1, 1)
        self.DenominatorLabel = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.DenominatorLabel.setFont(font)
        self.DenominatorLabel.setFrameShape(QtGui.QFrame.Box)
        self.DenominatorLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.DenominatorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DenominatorLabel.setObjectName(_fromUtf8("DenominatorLabel"))
        self.gridLayout.addWidget(self.DenominatorLabel, 2, 0, 1, 1)
        self.InputGroup = QtGui.QGroupBox(self.centralWidget)
        self.InputGroup.setGeometry(QtCore.QRect(270, 320, 521, 221))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.InputGroup.setFont(font)
        self.InputGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.InputGroup.setObjectName(_fromUtf8("InputGroup"))
        self.WaveTypeGroup = QtGui.QGroupBox(self.InputGroup)
        self.WaveTypeGroup.setGeometry(QtCore.QRect(10, 20, 161, 131))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.WaveTypeGroup.setFont(font)
        self.WaveTypeGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.WaveTypeGroup.setObjectName(_fromUtf8("WaveTypeGroup"))
        self.WaveTypeComboBox = QtGui.QComboBox(self.WaveTypeGroup)
        self.WaveTypeComboBox.setGeometry(QtCore.QRect(10, 60, 141, 22))
        self.WaveTypeComboBox.setMaxVisibleItems(10)
        self.WaveTypeComboBox.setObjectName(_fromUtf8("WaveTypeComboBox"))
        self.WaveTypeComboBox.addItem(_fromUtf8(""))
        self.WaveTypeComboBox.addItem(_fromUtf8(""))
        self.WaveTypeComboBox.addItem(_fromUtf8(""))
        self.WaveTypeComboBox.addItem(_fromUtf8(""))
        self.WaveParametersGroup = QtGui.QGroupBox(self.InputGroup)
        self.WaveParametersGroup.setGeometry(QtCore.QRect(190, 20, 121, 131))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.WaveParametersGroup.setFont(font)
        self.WaveParametersGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.WaveParametersGroup.setObjectName(_fromUtf8("WaveParametersGroup"))
        self.MagnitudeLabel = QtGui.QLabel(self.WaveParametersGroup)
        self.MagnitudeLabel.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.MagnitudeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MagnitudeLabel.setObjectName(_fromUtf8("MagnitudeLabel"))
        self.Magnitude = QtGui.QLineEdit(self.WaveParametersGroup)
        self.Magnitude.setGeometry(QtCore.QRect(10, 40, 99, 20))
        self.Magnitude.setAlignment(QtCore.Qt.AlignCenter)
        self.Magnitude.setObjectName(_fromUtf8("Magnitude"))
        self.FrequencyLabel = QtGui.QLabel(self.WaveParametersGroup)
        self.FrequencyLabel.setGeometry(QtCore.QRect(10, 70, 101, 21))
        self.FrequencyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FrequencyLabel.setObjectName(_fromUtf8("FrequencyLabel"))
        self.Frequency = QtGui.QLineEdit(self.WaveParametersGroup)
        self.Frequency.setGeometry(QtCore.QRect(10, 100, 99, 20))
        self.Frequency.setAlignment(QtCore.Qt.AlignCenter)
        self.Frequency.setObjectName(_fromUtf8("Frequency"))
        self.ManualCommandGroup = QtGui.QGroupBox(self.InputGroup)
        self.ManualCommandGroup.setGeometry(QtCore.QRect(330, 20, 181, 131))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ManualCommandGroup.setFont(font)
        self.ManualCommandGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.ManualCommandGroup.setObjectName(_fromUtf8("ManualCommandGroup"))
        self.JogDownButton = QtGui.QPushButton(self.ManualCommandGroup)
        self.JogDownButton.setGeometry(QtCore.QRect(20, 80, 51, 31))
        self.JogDownButton.setObjectName(_fromUtf8("JogDownButton"))
        self.JogUpButton = QtGui.QPushButton(self.ManualCommandGroup)
        self.JogUpButton.setGeometry(QtCore.QRect(20, 30, 51, 31))
        self.JogUpButton.setObjectName(_fromUtf8("JogUpButton"))
        self.CommandLabel = QtGui.QLabel(self.ManualCommandGroup)
        self.CommandLabel.setGeometry(QtCore.QRect(90, 20, 69, 21))
        self.CommandLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CommandLabel.setObjectName(_fromUtf8("CommandLabel"))
        self.Command = QtGui.QLineEdit(self.ManualCommandGroup)
        self.Command.setGeometry(QtCore.QRect(90, 40, 69, 21))
        self.Command.setAlignment(QtCore.Qt.AlignCenter)
        self.Command.setObjectName(_fromUtf8("Command"))
        self.StepSizeLabel = QtGui.QLabel(self.ManualCommandGroup)
        self.StepSizeLabel.setGeometry(QtCore.QRect(90, 60, 69, 21))
        self.StepSizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StepSizeLabel.setObjectName(_fromUtf8("StepSizeLabel"))
        self.StepSize = QtGui.QLineEdit(self.ManualCommandGroup)
        self.StepSize.setGeometry(QtCore.QRect(90, 80, 69, 20))
        self.StepSize.setAlignment(QtCore.Qt.AlignCenter)
        self.StepSize.setObjectName(_fromUtf8("StepSize"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.InputGroup)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 160, 501, 61))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.RunWaveAutoSaveButton = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 255, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 255, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.RunWaveAutoSaveButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.RunWaveAutoSaveButton.setFont(font)
        self.RunWaveAutoSaveButton.setCheckable(True)
        self.RunWaveAutoSaveButton.setObjectName(_fromUtf8("RunWaveAutoSaveButton"))
        self.horizontalLayout.addWidget(self.RunWaveAutoSaveButton)
        self.RunWaveContinuousButton = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.RunWaveContinuousButton.setFont(font)
        self.RunWaveContinuousButton.setCheckable(True)
        self.RunWaveContinuousButton.setObjectName(_fromUtf8("RunWaveContinuousButton"))
        self.horizontalLayout.addWidget(self.RunWaveContinuousButton)
        self.DisplayGroup = QtGui.QGroupBox(self.centralWidget)
        self.DisplayGroup.setGeometry(QtCore.QRect(800, 360, 191, 181))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DisplayGroup.setFont(font)
        self.DisplayGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.DisplayGroup.setCheckable(False)
        self.DisplayGroup.setObjectName(_fromUtf8("DisplayGroup"))
        self.gridLayoutWidget_6 = QtGui.QWidget(self.DisplayGroup)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 171, 151))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_3.setMargin(11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.ResetEncodersButton = QtGui.QPushButton(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ResetEncodersButton.setFont(font)
        self.ResetEncodersButton.setObjectName(_fromUtf8("ResetEncodersButton"))
        self.gridLayout_3.addWidget(self.ResetEncodersButton, 2, 0, 1, 2)
        self.PositionLabel = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.PositionLabel.setFont(font)
        self.PositionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PositionLabel.setObjectName(_fromUtf8("PositionLabel"))
        self.gridLayout_3.addWidget(self.PositionLabel, 0, 0, 1, 1)
        self.Speed = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Speed.setFont(font)
        self.Speed.setAlignment(QtCore.Qt.AlignCenter)
        self.Speed.setObjectName(_fromUtf8("Speed"))
        self.gridLayout_3.addWidget(self.Speed, 1, 1, 1, 1)
        self.Position = QtGui.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Position.setFont(font)
        self.Position.setAlignment(QtCore.Qt.AlignCenter)
        self.Position.setObjectName(_fromUtf8("Position"))
        self.gridLayout_3.addWidget(self.Position, 0, 1, 1, 1)
        self.SpeedLabel = QtGui.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.SpeedLabel.setFont(font)
        self.SpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SpeedLabel.setObjectName(_fromUtf8("SpeedLabel"))
        self.gridLayout_3.addWidget(self.SpeedLabel, 1, 0, 1, 1)
        self.ModelGroup_2 = QtGui.QGroupBox(self.centralWidget)
        self.ModelGroup_2.setGeometry(QtCore.QRect(800, 190, 191, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ModelGroup_2.setFont(font)
        self.ModelGroup_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ModelGroup_2.setObjectName(_fromUtf8("ModelGroup_2"))
        self.TransferFunctionGroup_2 = QtGui.QGroupBox(self.ModelGroup_2)
        self.TransferFunctionGroup_2.setGeometry(QtCore.QRect(10, 20, 171, 141))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.TransferFunctionGroup_2.setFont(font)
        self.TransferFunctionGroup_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TransferFunctionGroup_2.setObjectName(_fromUtf8("TransferFunctionGroup_2"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.TransferFunctionGroup_2)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 151, 111))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_4.setMargin(11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.NumeratorCL = QtGui.QLineEdit(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.NumeratorCL.setFont(font)
        self.NumeratorCL.setAlignment(QtCore.Qt.AlignCenter)

        self.NumeratorCL.setObjectName(_fromUtf8("NumeratorCL"))
        self.gridLayout_4.addWidget(self.NumeratorCL, 1, 0, 1, 1)
        self.DenominatorCL = QtGui.QLineEdit(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.DenominatorCL.setFont(font)
        self.DenominatorCL.setAlignment(QtCore.Qt.AlignCenter)

        self.DenominatorCL.setObjectName(_fromUtf8("DenominatorCL"))
        self.gridLayout_4.addWidget(self.DenominatorCL, 3, 0, 1, 1)
        self.NumeratorLabel2 = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.NumeratorLabel2.setFont(font)
        self.NumeratorLabel2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NumeratorLabel2.setAutoFillBackground(False)
        self.NumeratorLabel2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.NumeratorLabel2.setFrameShape(QtGui.QFrame.Box)
        self.NumeratorLabel2.setFrameShadow(QtGui.QFrame.Sunken)
        self.NumeratorLabel2.setTextFormat(QtCore.Qt.AutoText)
        self.NumeratorLabel2.setScaledContents(False)
        self.NumeratorLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.NumeratorLabel2.setObjectName(_fromUtf8("NumeratorLabel2"))
        self.gridLayout_4.addWidget(self.NumeratorLabel2, 0, 0, 1, 1)
        self.DenominatorLabel2 = QtGui.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.DenominatorLabel2.setFont(font)
        self.DenominatorLabel2.setFrameShape(QtGui.QFrame.Box)
        self.DenominatorLabel2.setFrameShadow(QtGui.QFrame.Sunken)
        self.DenominatorLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.DenominatorLabel2.setObjectName(_fromUtf8("DenominatorLabel2"))
        self.gridLayout_4.addWidget(self.DenominatorLabel2, 2, 0, 1, 1)
        self.OpenFlashDir = QtGui.QToolButton(self.centralWidget)
        self.OpenFlashDir.setGeometry(QtCore.QRect(240, 460, 25, 21))
        self.OpenFlashDir.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.OpenFlashDir.setObjectName(_fromUtf8("OpenFlashDir"))
        self.FlashMotorLabDir = QtGui.QLineEdit(self.centralWidget)
        self.FlashMotorLabDir.setGeometry(QtCore.QRect(100, 460, 141, 21))
        self.FlashMotorLabDir.setObjectName(_fromUtf8("FlashMotorLabDir"))
        self.COMPortComboBox = QtGui.QComboBox(self.centralWidget)
        self.COMPortComboBox.setGeometry(QtCore.QRect(10, 510, 81, 22))
        self.COMPortComboBox.setObjectName(_fromUtf8("COMPortComboBox"))
        self.COMPortComboBox.addItem(_fromUtf8(""))
        self.RefreshComButton = QtGui.QPushButton(self.centralWidget)
        self.RefreshComButton.setGeometry(QtCore.QRect(100, 512, 75, 21))
        self.RefreshComButton.setObjectName(_fromUtf8("RefreshComButton"))
        self.ConnectComButton = QtGui.QPushButton(self.centralWidget)
        self.ConnectComButton.setGeometry(QtCore.QRect(180, 512, 81, 21))
        self.ConnectComButton.setObjectName(_fromUtf8("ConnectComButton"))
        self.ConnectComButton.setCheckable(True)
        self.FlashButton = QtGui.QPushButton(self.centralWidget)
        self.FlashButton.setGeometry(QtCore.QRect(10, 460, 81, 21))
        self.FlashButton.setObjectName(_fromUtf8("FlashButton"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(10, 490, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        Motorlab.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(Motorlab)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1004, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        Motorlab.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(Motorlab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainToolBar.sizePolicy().hasHeightForWidth())
        self.mainToolBar.setSizePolicy(sizePolicy)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        Motorlab.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(Motorlab)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        Motorlab.setStatusBar(self.statusBar)
        

        self.retranslateUi(Motorlab)
        QtCore.QMetaObject.connectSlotsByName(Motorlab)

    def retranslateUi(self, Motorlab):
        Motorlab.setWindowTitle(_translate("Motorlab", "Motorlab", None))
        self.ControllerGroup.setTitle(_translate("Motorlab", "Controller", None))
        self.KdLabel.setText(_translate("Motorlab", "Kd", None))
        self.KiLabel.setText(_translate("Motorlab", "Ki", None))
        self.Kd.setText(_translate("Motorlab", "0", None))
        self.Ki.setText(_translate("Motorlab", "0", None))
        self.Kp.setText(_translate("Motorlab", "0", None))
        self.KpLabel.setText(_translate("Motorlab", "Kp", None))
        self.OLRadioButton.setText(_translate("Motorlab", "Open Loop", None))
        self.PosConRadioButton.setText(_translate("Motorlab", "Position Control", None))
        self.SpeedConRadioButton.setText(_translate("Motorlab", "Speed Control", None))
        self.DataCollectionGroup.setTitle(_translate("Motorlab", "Data Collection", None))
        self.FileName.setText(_translate("Motorlab", "Data", None))
        self.SampleRateLabel.setText(_translate("Motorlab", "Sample Rate (Hz)", None))
        self.FileVariableNameLabel.setText(_translate("Motorlab", "File/Variable Name", None))
        self.Duration.setText(_translate("Motorlab", "2.34", None))
        self.SampleCount.setText(_translate("Motorlab", "500", None))
        self.SampleCountLabel.setText(_translate("Motorlab", "Sample Count", None))
        self.DurationLabel.setText(_translate("Motorlab", "Duration (sec)", None))
        self.SampleRate.setText(_translate("Motorlab", "100", None))
        self.OpenPython.setText(_translate("Motorlab", "Open Python", None))
        self.StartButton.setText(_translate("Motorlab", "Start", None))
        self.CollectDataButton.setText(_translate("Motorlab", "Collect Data", None))
        self.StopButton.setText(_translate("Motorlab", "Stop", None))
        self.StartAndCollectButton.setText(_translate("Motorlab", "Start + Collect", None))
        self.OpenDirectoryButton.setText(_translate("Motorlab", "Open Directory", None))
        self.GenerateFileButton.setText(_translate("Motorlab", "Generate File", None))
        self.DataExplorerGroup.setTitle(_translate("Motorlab", "Data Explorer", None))
        self.DataExplorer.setHtml(_translate("Motorlab", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">MotorLab v1.0</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.PlotToolsGroup.setTitle(_translate("Motorlab", "Plot Tools", None))
        self.DataPlotGroup.setTitle(_translate("Motorlab", "Data Plot", None))
        self.PlotDataButton.setText(_translate("Motorlab", "Plot Data", None))
        self.ModelPlotGroup.setTitle(_translate("Motorlab", "Model Plot", None))
        self.StepModelButton.setText(_translate("Motorlab", "Step Model", None))
        self.BodeModelButton.setText(_translate("Motorlab", "Bode Model", None))
        self.ComparisonGroup.setTitle(_translate("Motorlab", "Comparison Plot", None))
        self.DataModelButton.setText(_translate("Motorlab", " Data + Model", None))
        self.FitDataCheckBox.setText(_translate("Motorlab", "Fit Data", None))
        self.PlotAutoFormatCheckBox.setText(_translate("Motorlab", "AutoFormat", None))
        self.PlotAllDataCheckBox.setText(_translate("Motorlab", "Plot All Data", None))
        self.checkBox.setText(_translate("Motorlab", "Experiment", None))
        self.ModelGroup.setTitle(_translate("Motorlab", "OL Model", None))
        self.TransferFunctionGroup.setTitle(_translate("Motorlab", "Transfer Function", None))
        self.Numerator.setText(_translate("Motorlab", "1,2", None))
        self.Denominator.setText(_translate("Motorlab", "1,0.7,3", None))
        self.NumeratorLabel.setText(_translate("Motorlab", "Numerator", None))
        self.DenominatorLabel.setText(_translate("Motorlab", "Denominator", None))
        self.InputGroup.setTitle(_translate("Motorlab", "Input", None))
        self.WaveTypeGroup.setTitle(_translate("Motorlab", "Wave Type", None))
        self.WaveTypeComboBox.setItemText(0, _translate("Motorlab", "Sine", None))
        self.WaveTypeComboBox.setItemText(1, _translate("Motorlab", "Square", None))
        self.WaveTypeComboBox.setItemText(2, _translate("Motorlab", "Triangle", None))
        self.WaveTypeComboBox.setItemText(3, _translate("Motorlab", "Trapezoidal", None))
        self.WaveParametersGroup.setTitle(_translate("Motorlab", "Wave Parameters", None))
        self.MagnitudeLabel.setText(_translate("Motorlab", "Magnitude", None))
        self.Magnitude.setText(_translate("Motorlab", "1", None))
        self.FrequencyLabel.setText(_translate("Motorlab", "Frequency (Hz)", None))
        self.Frequency.setText(_translate("Motorlab", "1", None))
        self.ManualCommandGroup.setTitle(_translate("Motorlab", "Manual Command", None))
        self.JogDownButton.setText(_translate("Motorlab", "-", None))
        self.JogUpButton.setText(_translate("Motorlab", "+", None))
        self.CommandLabel.setText(_translate("Motorlab", "Command", None))
        self.Command.setText(_translate("Motorlab", "0", None))
        self.StepSizeLabel.setText(_translate("Motorlab", "Step Size", None))
        self.StepSize.setText(_translate("Motorlab", "1.0", None))
        self.RunWaveAutoSaveButton.setText(_translate("Motorlab", "Run Wave AutoSave", None))
        self.RunWaveContinuousButton.setText(_translate("Motorlab", "Run Wave Continuous", None))
        self.DisplayGroup.setTitle(_translate("Motorlab", "Display", None))
        self.ResetEncodersButton.setText(_translate("Motorlab", "Reset Encoders", None))
        self.PositionLabel.setText(_translate("Motorlab", "Position (Deg)", None))
        self.Speed.setText(_translate("Motorlab", "0", None))
        self.Position.setText(_translate("Motorlab", "0", None))
        self.SpeedLabel.setText(_translate("Motorlab", "Speed (RPM)", None))
        self.ModelGroup_2.setTitle(_translate("Motorlab", "CL Model", None))
        self.TransferFunctionGroup_2.setTitle(_translate("Motorlab", "Transfer Function", None))
        self.NumeratorCL.setText(_translate("Motorlab", "1,2", None))
        self.DenominatorCL.setText(_translate("Motorlab", "1,0.7,3", None))
        self.NumeratorLabel2.setText(_translate("Motorlab", "Numerator", None))
        self.DenominatorLabel2.setText(_translate("Motorlab", "Denominator", None))
        self.OpenFlashDir.setText(_translate("Motorlab", "...", None))
        self.FlashMotorLabDir.setText(_translate("Motorlab", "Flash .bat to Motorlab", None))
        self.COMPortComboBox.setItemText(0, _translate("Motorlab", "", None))
        self.RefreshComButton.setText(_translate("Motorlab", "Refresh", None))
        self.ConnectComButton.setText(_translate("Motorlab", "Connect", None))
        self.FlashButton.setText(_translate("Motorlab", "Flash", None))
        self.label.setText(_translate("Motorlab", "Connect to the Motorlab", None))

