# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'motorlabuiv2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Motorlab(object):
    def setupUi(self, Motorlab):
        Motorlab.setObjectName("Motorlab")
        Motorlab.resize(1493, 612)
        Motorlab.setAutoFillBackground(False)
        Motorlab.setDocumentMode(False)
        self.centralWidget = QtWidgets.QWidget(Motorlab)
        self.centralWidget.setObjectName("centralWidget")
        self.ControllerGroup = QtWidgets.QGroupBox(self.centralWidget)
        self.ControllerGroup.setGeometry(QtCore.QRect(10, 320, 251, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.ControllerGroup.setFont(font)
        self.ControllerGroup.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ControllerGroup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ControllerGroup.setAutoFillBackground(False)
        self.ControllerGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.ControllerGroup.setObjectName("ControllerGroup")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.ControllerGroup)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 231, 101))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.ParametersLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.ParametersLayout.setContentsMargins(11, 11, 11, 11)
        self.ParametersLayout.setSpacing(6)
        self.ParametersLayout.setObjectName("ParametersLayout")
        self.KdLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.KdLabel.setFont(font)
        self.KdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.KdLabel.setObjectName("KdLabel")
        self.ParametersLayout.addWidget(self.KdLabel, 1, 0, 1, 1)
        self.KiLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.KiLabel.setFont(font)
        self.KiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.KiLabel.setObjectName("KiLabel")
        self.ParametersLayout.addWidget(self.KiLabel, 2, 0, 1, 1)
        self.Kd = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Kd.setFont(font)
        self.Kd.setAlignment(QtCore.Qt.AlignCenter)
        self.Kd.setObjectName("Kd")
        self.ParametersLayout.addWidget(self.Kd, 1, 1, 1, 1)
        self.Ki = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Ki.setFont(font)
        self.Ki.setAlignment(QtCore.Qt.AlignCenter)
        self.Ki.setObjectName("Ki")
        self.ParametersLayout.addWidget(self.Ki, 2, 1, 1, 1)
        self.Kp = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Kp.setFont(font)
        self.Kp.setAlignment(QtCore.Qt.AlignCenter)
        self.Kp.setObjectName("Kp")
        self.ParametersLayout.addWidget(self.Kp, 0, 1, 1, 1)
        self.KpLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KpLabel.sizePolicy().hasHeightForWidth())
        self.KpLabel.setSizePolicy(sizePolicy)
        self.KpLabel.setMinimumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.KpLabel.setFont(font)
        self.KpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.KpLabel.setObjectName("KpLabel")
        self.ParametersLayout.addWidget(self.KpLabel, 0, 0, 1, 1)
        self.OLRadioButton = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.OLRadioButton.setFont(font)
        self.OLRadioButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OLRadioButton.setChecked(True)
        self.OLRadioButton.setObjectName("OLRadioButton")
        self.ParametersLayout.addWidget(self.OLRadioButton, 0, 2, 1, 1)
        self.PosConRadioButton = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.PosConRadioButton.setFont(font)
        self.PosConRadioButton.setObjectName("PosConRadioButton")
        self.ParametersLayout.addWidget(self.PosConRadioButton, 1, 2, 1, 1)
        self.SpeedConRadioButton = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.SpeedConRadioButton.setFont(font)
        self.SpeedConRadioButton.setObjectName("SpeedConRadioButton")
        self.ParametersLayout.addWidget(self.SpeedConRadioButton, 2, 2, 1, 1)
        self.DataCollectionGroup = QtWidgets.QGroupBox(self.centralWidget)
        self.DataCollectionGroup.setGeometry(QtCore.QRect(10, 10, 251, 301))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.DataCollectionGroup.setFont(font)
        self.DataCollectionGroup.setAcceptDrops(False)
        self.DataCollectionGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.DataCollectionGroup.setFlat(False)
        self.DataCollectionGroup.setCheckable(False)
        self.DataCollectionGroup.setObjectName("DataCollectionGroup")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.DataCollectionGroup)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 231, 111))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.DataCollectionLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.DataCollectionLayout.setContentsMargins(11, 11, 11, 11)
        self.DataCollectionLayout.setSpacing(6)
        self.DataCollectionLayout.setObjectName("DataCollectionLayout")
        self.FileName = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.FileName.setFont(font)
        self.FileName.setAlignment(QtCore.Qt.AlignCenter)
        self.FileName.setObjectName("FileName")
        self.DataCollectionLayout.addWidget(self.FileName, 3, 1, 1, 1)
        self.SampleRateLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.SampleRateLabel.setFont(font)
        self.SampleRateLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SampleRateLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SampleRateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SampleRateLabel.setObjectName("SampleRateLabel")
        self.DataCollectionLayout.addWidget(self.SampleRateLabel, 0, 0, 1, 1)
        self.FileVariableNameLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.FileVariableNameLabel.setFont(font)
        self.FileVariableNameLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.FileVariableNameLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.FileVariableNameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FileVariableNameLabel.setObjectName("FileVariableNameLabel")
        self.DataCollectionLayout.addWidget(self.FileVariableNameLabel, 3, 0, 1, 1)
        self.Duration = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Duration.setFont(font)
        self.Duration.setAlignment(QtCore.Qt.AlignCenter)
        self.Duration.setObjectName("Duration")
        self.DataCollectionLayout.addWidget(self.Duration, 2, 1, 1, 1)
        self.SampleCount = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.SampleCount.setFont(font)
        self.SampleCount.setAlignment(QtCore.Qt.AlignCenter)
        self.SampleCount.setObjectName("SampleCount")
        self.DataCollectionLayout.addWidget(self.SampleCount, 1, 1, 1, 1)
        self.SampleCountLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.SampleCountLabel.setFont(font)
        self.SampleCountLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SampleCountLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SampleCountLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SampleCountLabel.setObjectName("SampleCountLabel")
        self.DataCollectionLayout.addWidget(self.SampleCountLabel, 1, 0, 1, 1)
        self.DurationLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.DurationLabel.setFont(font)
        self.DurationLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DurationLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DurationLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.DurationLabel.setObjectName("DurationLabel")
        self.DataCollectionLayout.addWidget(self.DurationLabel, 2, 0, 1, 1)
        self.SampleRate = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.SampleRate.setFont(font)
        self.SampleRate.setAlignment(QtCore.Qt.AlignCenter)
        self.SampleRate.setClearButtonEnabled(False)
        self.SampleRate.setObjectName("SampleRate")
        self.DataCollectionLayout.addWidget(self.SampleRate, 0, 1, 1, 1)
        self.DataButtonGroup = QtWidgets.QGroupBox(self.DataCollectionGroup)
        self.DataButtonGroup.setGeometry(QtCore.QRect(10, 140, 231, 151))
        self.DataButtonGroup.setTitle("")
        self.DataButtonGroup.setObjectName("DataButtonGroup")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.DataButtonGroup)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 211, 131))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.DataButtonsLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.DataButtonsLayout.setContentsMargins(11, 11, 11, 11)
        self.DataButtonsLayout.setSpacing(6)
        self.DataButtonsLayout.setObjectName("DataButtonsLayout")
        self.OpenPython = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.OpenPython.setFont(font)
        self.OpenPython.setObjectName("OpenPython")
        self.DataButtonsLayout.addWidget(self.OpenPython, 3, 1, 1, 1)
        self.StartButton = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.StartButton.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.StartButton.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.StartButton.setFont(font)
        self.StartButton.setCheckable(True)
        self.StartButton.setChecked(False)
        self.StartButton.setAutoDefault(False)
        self.StartButton.setDefault(False)
        self.StartButton.setFlat(False)
        self.StartButton.setObjectName("StartButton")
        self.DataButtonsLayout.addWidget(self.StartButton, 1, 0, 1, 2)
        self.CollectDataButton = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.CollectDataButton.setFont(font)
        self.CollectDataButton.setCheckable(True)
        self.CollectDataButton.setObjectName("CollectDataButton")
        self.DataButtonsLayout.addWidget(self.CollectDataButton, 3, 0, 1, 1)
        self.StopButton = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.StopButton.setFont(font)
        self.StopButton.setObjectName("StopButton")
        self.DataButtonsLayout.addWidget(self.StopButton, 2, 1, 1, 1)
        self.StartAndCollectButton = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.StartAndCollectButton.setFont(font)
        self.StartAndCollectButton.setCheckable(True)
        self.StartAndCollectButton.setObjectName("StartAndCollectButton")
        self.DataButtonsLayout.addWidget(self.StartAndCollectButton, 2, 0, 1, 1)
        self.OpenDirectoryButton = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.OpenDirectoryButton.setFont(font)
        self.OpenDirectoryButton.setObjectName("OpenDirectoryButton")
        self.DataButtonsLayout.addWidget(self.OpenDirectoryButton, 0, 0, 1, 1)
        self.GenerateFileButton = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.GenerateFileButton.setFont(font)
        self.GenerateFileButton.setObjectName("GenerateFileButton")
        self.DataButtonsLayout.addWidget(self.GenerateFileButton, 0, 1, 1, 1)
        self.DataExplorerGroup = QtWidgets.QGroupBox(self.centralWidget)
        self.DataExplorerGroup.setGeometry(QtCore.QRect(270, 10, 281, 311))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DataExplorerGroup.setFont(font)
        self.DataExplorerGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.DataExplorerGroup.setObjectName("DataExplorerGroup")
        self.DataExplorer = QtWidgets.QTextBrowser(self.DataExplorerGroup)
        self.DataExplorer.setGeometry(QtCore.QRect(10, 20, 261, 281))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.DataExplorer.setFont(font)
        self.DataExplorer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DataExplorer.setObjectName("DataExplorer")
        self.PlotToolsGroup = QtWidgets.QGroupBox(self.centralWidget)
        self.PlotToolsGroup.setGeometry(QtCore.QRect(560, 10, 231, 311))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PlotToolsGroup.setFont(font)
        self.PlotToolsGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.PlotToolsGroup.setObjectName("PlotToolsGroup")
        self.DataPlotGroup = QtWidgets.QGroupBox(self.PlotToolsGroup)
        self.DataPlotGroup.setGeometry(QtCore.QRect(10, 20, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.DataPlotGroup.setFont(font)
        self.DataPlotGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.DataPlotGroup.setObjectName("DataPlotGroup")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.DataPlotGroup)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 191, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PlotDataButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.PlotDataButton.setFont(font)
        self.PlotDataButton.setCheckable(False)
        self.PlotDataButton.setChecked(False)
        self.PlotDataButton.setDefault(False)
        self.PlotDataButton.setFlat(False)
        self.PlotDataButton.setObjectName("PlotDataButton")
        self.horizontalLayout_2.addWidget(self.PlotDataButton)
        self.ModelPlotGroup = QtWidgets.QGroupBox(self.PlotToolsGroup)
        self.ModelPlotGroup.setGeometry(QtCore.QRect(10, 100, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ModelPlotGroup.setFont(font)
        self.ModelPlotGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.ModelPlotGroup.setObjectName("ModelPlotGroup")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.ModelPlotGroup)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 191, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.StepModelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.StepModelButton.setFont(font)
        self.StepModelButton.setFlat(False)
        self.StepModelButton.setObjectName("StepModelButton")
        self.horizontalLayout_3.addWidget(self.StepModelButton)
        self.BodeModelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.BodeModelButton.setFont(font)
        self.BodeModelButton.setAutoFillBackground(False)
        self.BodeModelButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.BodeModelButton.setFlat(False)
        self.BodeModelButton.setObjectName("BodeModelButton")
        self.horizontalLayout_3.addWidget(self.BodeModelButton)
        self.ComparisonGroup = QtWidgets.QGroupBox(self.PlotToolsGroup)
        self.ComparisonGroup.setGeometry(QtCore.QRect(10, 170, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ComparisonGroup.setFont(font)
        self.ComparisonGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.ComparisonGroup.setObjectName("ComparisonGroup")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.ComparisonGroup)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 191, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.DataModelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.DataModelButton.setFont(font)
        self.DataModelButton.setFlat(False)
        self.DataModelButton.setObjectName("DataModelButton")
        self.horizontalLayout_4.addWidget(self.DataModelButton)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.PlotToolsGroup)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 240, 195, 71))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.FitDataCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.FitDataCheckBox.setFont(font)
        self.FitDataCheckBox.setObjectName("FitDataCheckBox")
        self.gridLayout_2.addWidget(self.FitDataCheckBox, 1, 0, 1, 1)
        self.PlotAutoFormatCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.PlotAutoFormatCheckBox.setFont(font)
        self.PlotAutoFormatCheckBox.setChecked(False)
        self.PlotAutoFormatCheckBox.setObjectName("PlotAutoFormatCheckBox")
        self.gridLayout_2.addWidget(self.PlotAutoFormatCheckBox, 2, 0, 1, 1)
        self.PlotAllDataCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.PlotAllDataCheckBox.setFont(font)
        self.PlotAllDataCheckBox.setObjectName("PlotAllDataCheckBox")
        self.gridLayout_2.addWidget(self.PlotAllDataCheckBox, 1, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 2, 1, 1, 1)
        self.ModelGroup = QtWidgets.QGroupBox(self.centralWidget)
        self.ModelGroup.setGeometry(QtCore.QRect(800, 10, 191, 181))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ModelGroup.setFont(font)
        self.ModelGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.ModelGroup.setObjectName("ModelGroup")
        self.TransferFunctionGroup = QtWidgets.QGroupBox(self.ModelGroup)
        self.TransferFunctionGroup.setGeometry(QtCore.QRect(10, 20, 171, 141))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.TransferFunctionGroup.setFont(font)
        self.TransferFunctionGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.TransferFunctionGroup.setObjectName("TransferFunctionGroup")
        self.gridLayoutWidget = QtWidgets.QWidget(self.TransferFunctionGroup)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 151, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.Numerator = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Numerator.setFont(font)
        self.Numerator.setAlignment(QtCore.Qt.AlignCenter)
        self.Numerator.setClearButtonEnabled(False)
        self.Numerator.setObjectName("Numerator")
        self.gridLayout.addWidget(self.Numerator, 1, 0, 1, 1)
        self.Denominator = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Denominator.setFont(font)
        self.Denominator.setAlignment(QtCore.Qt.AlignCenter)
        self.Denominator.setClearButtonEnabled(False)
        self.Denominator.setObjectName("Denominator")
        self.gridLayout.addWidget(self.Denominator, 3, 0, 1, 1)
        self.NumeratorLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.NumeratorLabel.setFont(font)
        self.NumeratorLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NumeratorLabel.setAutoFillBackground(False)
        self.NumeratorLabel.setInputMethodHints(QtCore.Qt.ImhNone)
        self.NumeratorLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.NumeratorLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.NumeratorLabel.setTextFormat(QtCore.Qt.AutoText)
        self.NumeratorLabel.setScaledContents(False)
        self.NumeratorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NumeratorLabel.setObjectName("NumeratorLabel")
        self.gridLayout.addWidget(self.NumeratorLabel, 0, 0, 1, 1)
        self.DenominatorLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.DenominatorLabel.setFont(font)
        self.DenominatorLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.DenominatorLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.DenominatorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DenominatorLabel.setObjectName("DenominatorLabel")
        self.gridLayout.addWidget(self.DenominatorLabel, 2, 0, 1, 1)
        self.InputGroup = QtWidgets.QGroupBox(self.centralWidget)
        self.InputGroup.setGeometry(QtCore.QRect(270, 320, 521, 221))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.InputGroup.setFont(font)
        self.InputGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.InputGroup.setObjectName("InputGroup")
        self.WaveTypeGroup = QtWidgets.QGroupBox(self.InputGroup)
        self.WaveTypeGroup.setGeometry(QtCore.QRect(10, 20, 161, 131))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.WaveTypeGroup.setFont(font)
        self.WaveTypeGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.WaveTypeGroup.setObjectName("WaveTypeGroup")
        self.WaveTypeComboBox = QtWidgets.QComboBox(self.WaveTypeGroup)
        self.WaveTypeComboBox.setGeometry(QtCore.QRect(10, 60, 141, 22))
        self.WaveTypeComboBox.setMaxVisibleItems(10)
        self.WaveTypeComboBox.setObjectName("WaveTypeComboBox")
        self.WaveTypeComboBox.addItem("")
        self.WaveTypeComboBox.addItem("")
        self.WaveTypeComboBox.addItem("")
        self.WaveTypeComboBox.addItem("")
        self.WaveParametersGroup = QtWidgets.QGroupBox(self.InputGroup)
        self.WaveParametersGroup.setGeometry(QtCore.QRect(190, 20, 121, 131))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.WaveParametersGroup.setFont(font)
        self.WaveParametersGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.WaveParametersGroup.setObjectName("WaveParametersGroup")
        self.MagnitudeLabel = QtWidgets.QLabel(self.WaveParametersGroup)
        self.MagnitudeLabel.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.MagnitudeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MagnitudeLabel.setObjectName("MagnitudeLabel")
        self.Magnitude = QtWidgets.QLineEdit(self.WaveParametersGroup)
        self.Magnitude.setGeometry(QtCore.QRect(10, 40, 99, 20))
        self.Magnitude.setAlignment(QtCore.Qt.AlignCenter)
        self.Magnitude.setObjectName("Magnitude")
        self.FrequencyLabel = QtWidgets.QLabel(self.WaveParametersGroup)
        self.FrequencyLabel.setGeometry(QtCore.QRect(10, 70, 101, 21))
        self.FrequencyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FrequencyLabel.setObjectName("FrequencyLabel")
        self.Frequency = QtWidgets.QLineEdit(self.WaveParametersGroup)
        self.Frequency.setGeometry(QtCore.QRect(10, 100, 99, 20))
        self.Frequency.setAlignment(QtCore.Qt.AlignCenter)
        self.Frequency.setObjectName("Frequency")
        self.ManualCommandGroup = QtWidgets.QGroupBox(self.InputGroup)
        self.ManualCommandGroup.setGeometry(QtCore.QRect(330, 20, 181, 131))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ManualCommandGroup.setFont(font)
        self.ManualCommandGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.ManualCommandGroup.setObjectName("ManualCommandGroup")
        self.JogDownButton = QtWidgets.QPushButton(self.ManualCommandGroup)
        self.JogDownButton.setGeometry(QtCore.QRect(20, 80, 51, 31))
        self.JogDownButton.setObjectName("JogDownButton")
        self.JogUpButton = QtWidgets.QPushButton(self.ManualCommandGroup)
        self.JogUpButton.setGeometry(QtCore.QRect(20, 30, 51, 31))
        self.JogUpButton.setObjectName("JogUpButton")
        self.CommandLabel = QtWidgets.QLabel(self.ManualCommandGroup)
        self.CommandLabel.setGeometry(QtCore.QRect(90, 20, 69, 21))
        self.CommandLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CommandLabel.setObjectName("CommandLabel")
        self.Command = QtWidgets.QLineEdit(self.ManualCommandGroup)
        self.Command.setGeometry(QtCore.QRect(90, 40, 69, 21))
        self.Command.setAlignment(QtCore.Qt.AlignCenter)
        self.Command.setObjectName("Command")
        self.StepSizeLabel = QtWidgets.QLabel(self.ManualCommandGroup)
        self.StepSizeLabel.setGeometry(QtCore.QRect(90, 60, 69, 21))
        self.StepSizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StepSizeLabel.setObjectName("StepSizeLabel")
        self.StepSize = QtWidgets.QLineEdit(self.ManualCommandGroup)
        self.StepSize.setGeometry(QtCore.QRect(90, 80, 69, 20))
        self.StepSize.setAlignment(QtCore.Qt.AlignCenter)
        self.StepSize.setObjectName("StepSize")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.InputGroup)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 160, 501, 61))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RunWaveAutoSaveButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 255, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 255, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.RunWaveAutoSaveButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.RunWaveAutoSaveButton.setFont(font)
        self.RunWaveAutoSaveButton.setCheckable(True)
        self.RunWaveAutoSaveButton.setObjectName("RunWaveAutoSaveButton")
        self.horizontalLayout.addWidget(self.RunWaveAutoSaveButton)
        self.RunWaveContinuousButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.RunWaveContinuousButton.setFont(font)
        self.RunWaveContinuousButton.setCheckable(True)
        self.RunWaveContinuousButton.setObjectName("RunWaveContinuousButton")
        self.horizontalLayout.addWidget(self.RunWaveContinuousButton)
        self.DisplayGroup = QtWidgets.QGroupBox(self.centralWidget)
        self.DisplayGroup.setGeometry(QtCore.QRect(800, 360, 191, 181))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DisplayGroup.setFont(font)
        self.DisplayGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.DisplayGroup.setCheckable(False)
        self.DisplayGroup.setObjectName("DisplayGroup")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.DisplayGroup)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 171, 151))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ResetEncodersButton = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ResetEncodersButton.setFont(font)
        self.ResetEncodersButton.setObjectName("ResetEncodersButton")
        self.gridLayout_3.addWidget(self.ResetEncodersButton, 2, 0, 1, 2)
        self.PositionLabel = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.PositionLabel.setFont(font)
        self.PositionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PositionLabel.setObjectName("PositionLabel")
        self.gridLayout_3.addWidget(self.PositionLabel, 0, 0, 1, 1)
        self.Speed = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Speed.setFont(font)
        self.Speed.setAlignment(QtCore.Qt.AlignCenter)
        self.Speed.setObjectName("Speed")
        self.gridLayout_3.addWidget(self.Speed, 1, 1, 1, 1)
        self.Position = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Position.setFont(font)
        self.Position.setAlignment(QtCore.Qt.AlignCenter)
        self.Position.setObjectName("Position")
        self.gridLayout_3.addWidget(self.Position, 0, 1, 1, 1)
        self.SpeedLabel = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.SpeedLabel.setFont(font)
        self.SpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SpeedLabel.setObjectName("SpeedLabel")
        self.gridLayout_3.addWidget(self.SpeedLabel, 1, 0, 1, 1)
        self.ModelGroup_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.ModelGroup_2.setGeometry(QtCore.QRect(800, 190, 191, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ModelGroup_2.setFont(font)
        self.ModelGroup_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ModelGroup_2.setObjectName("ModelGroup_2")
        self.TransferFunctionGroup_2 = QtWidgets.QGroupBox(self.ModelGroup_2)
        self.TransferFunctionGroup_2.setGeometry(QtCore.QRect(10, 20, 171, 141))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.TransferFunctionGroup_2.setFont(font)
        self.TransferFunctionGroup_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TransferFunctionGroup_2.setObjectName("TransferFunctionGroup_2")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.TransferFunctionGroup_2)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 151, 111))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.NumeratorCL = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.NumeratorCL.setFont(font)
        self.NumeratorCL.setAlignment(QtCore.Qt.AlignCenter)
        self.NumeratorCL.setClearButtonEnabled(False)
        self.NumeratorCL.setObjectName("NumeratorCL")
        self.gridLayout_4.addWidget(self.NumeratorCL, 1, 0, 1, 1)
        self.DenominatorCL = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.DenominatorCL.setFont(font)
        self.DenominatorCL.setAlignment(QtCore.Qt.AlignCenter)
        self.DenominatorCL.setClearButtonEnabled(False)
        self.DenominatorCL.setObjectName("DenominatorCL")
        self.gridLayout_4.addWidget(self.DenominatorCL, 3, 0, 1, 1)
        self.NumeratorLabel2 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.NumeratorLabel2.setFont(font)
        self.NumeratorLabel2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.NumeratorLabel2.setAutoFillBackground(False)
        self.NumeratorLabel2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.NumeratorLabel2.setFrameShape(QtWidgets.QFrame.Box)
        self.NumeratorLabel2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.NumeratorLabel2.setTextFormat(QtCore.Qt.AutoText)
        self.NumeratorLabel2.setScaledContents(False)
        self.NumeratorLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.NumeratorLabel2.setObjectName("NumeratorLabel2")
        self.gridLayout_4.addWidget(self.NumeratorLabel2, 0, 0, 1, 1)
        self.DenominatorLabel2 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.DenominatorLabel2.setFont(font)
        self.DenominatorLabel2.setFrameShape(QtWidgets.QFrame.Box)
        self.DenominatorLabel2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.DenominatorLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.DenominatorLabel2.setObjectName("DenominatorLabel2")
        self.gridLayout_4.addWidget(self.DenominatorLabel2, 2, 0, 1, 1)
        self.OpenFlashDir = QtWidgets.QToolButton(self.centralWidget)
        self.OpenFlashDir.setGeometry(QtCore.QRect(240, 460, 25, 21))
        self.OpenFlashDir.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.OpenFlashDir.setObjectName("OpenFlashDir")
        self.FlashMotorLabDir = QtWidgets.QLineEdit(self.centralWidget)
        self.FlashMotorLabDir.setGeometry(QtCore.QRect(100, 460, 141, 21))
        self.FlashMotorLabDir.setObjectName("FlashMotorLabDir")
        self.COMPortComboBox = QtWidgets.QComboBox(self.centralWidget)
        self.COMPortComboBox.setGeometry(QtCore.QRect(10, 510, 81, 22))
        self.COMPortComboBox.setObjectName("COMPortComboBox")
        self.COMPortComboBox.addItem("")
        self.RefreshComButton = QtWidgets.QPushButton(self.centralWidget)
        self.RefreshComButton.setGeometry(QtCore.QRect(100, 512, 75, 21))
        self.RefreshComButton.setObjectName("RefreshComButton")
        self.ConnectComButton = QtWidgets.QPushButton(self.centralWidget)
        self.ConnectComButton.setGeometry(QtCore.QRect(180, 512, 81, 21))
        self.ConnectComButton.setObjectName("ConnectComButton")
        self.FlashButton = QtWidgets.QPushButton(self.centralWidget)
        self.FlashButton.setGeometry(QtCore.QRect(10, 460, 81, 21))
        self.FlashButton.setObjectName("FlashButton")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(10, 490, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.ExperimentalArea = QtWidgets.QGroupBox(self.centralWidget)
        self.ExperimentalArea.setGeometry(QtCore.QRect(1010, 10, 471, 531))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ExperimentalArea.setFont(font)
        self.ExperimentalArea.setAlignment(QtCore.Qt.AlignCenter)
        self.ExperimentalArea.setObjectName("ExperimentalArea")
        self.Terminal = QtWidgets.QPlainTextEdit(self.ExperimentalArea)
        self.Terminal.setGeometry(QtCore.QRect(10, 20, 451, 471))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Terminal.setFont(font)
        self.Terminal.setObjectName("Terminal")
        self.RunButton = QtWidgets.QPushButton(self.ExperimentalArea)
        self.RunButton.setGeometry(QtCore.QRect(10, 500, 83, 24))
        self.RunButton.setObjectName("RunButton")
        Motorlab.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Motorlab)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1493, 19))
        self.menuBar.setObjectName("menuBar")
        Motorlab.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Motorlab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainToolBar.sizePolicy().hasHeightForWidth())
        self.mainToolBar.setSizePolicy(sizePolicy)
        self.mainToolBar.setObjectName("mainToolBar")
        Motorlab.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Motorlab)
        self.statusBar.setObjectName("statusBar")
        Motorlab.setStatusBar(self.statusBar)

        self.retranslateUi(Motorlab)
        QtCore.QMetaObject.connectSlotsByName(Motorlab)

    def retranslateUi(self, Motorlab):
        _translate = QtCore.QCoreApplication.translate
        Motorlab.setWindowTitle(_translate("Motorlab", "Motorlab"))
        self.ControllerGroup.setTitle(_translate("Motorlab", "Controller"))
        self.KdLabel.setText(_translate("Motorlab", "Kd"))
        self.KiLabel.setText(_translate("Motorlab", "Ki"))
        self.Kd.setText(_translate("Motorlab", "0"))
        self.Ki.setText(_translate("Motorlab", "0"))
        self.Kp.setText(_translate("Motorlab", "0"))
        self.KpLabel.setText(_translate("Motorlab", "Kp"))
        self.OLRadioButton.setText(_translate("Motorlab", "Open Loop"))
        self.PosConRadioButton.setText(_translate("Motorlab", "Position Control"))
        self.SpeedConRadioButton.setText(_translate("Motorlab", "Speed Control"))
        self.DataCollectionGroup.setTitle(_translate("Motorlab", "Data Collection"))
        self.FileName.setText(_translate("Motorlab", "Data"))
        self.SampleRateLabel.setText(_translate("Motorlab", "Sample Rate (Hz)"))
        self.FileVariableNameLabel.setText(_translate("Motorlab", "File/Variable Name"))
        self.Duration.setText(_translate("Motorlab", "2.34"))
        self.SampleCount.setText(_translate("Motorlab", "500"))
        self.SampleCountLabel.setText(_translate("Motorlab", "Sample Count"))
        self.DurationLabel.setText(_translate("Motorlab", "Duration (sec)"))
        self.SampleRate.setText(_translate("Motorlab", "100"))
        self.OpenPython.setText(_translate("Motorlab", "Open Python"))
        self.StartButton.setText(_translate("Motorlab", "Start"))
        self.CollectDataButton.setText(_translate("Motorlab", "Collect Data"))
        self.StopButton.setText(_translate("Motorlab", "Stop"))
        self.StartAndCollectButton.setText(_translate("Motorlab", "Start + Collect"))
        self.OpenDirectoryButton.setText(_translate("Motorlab", "Open Directory"))
        self.GenerateFileButton.setText(_translate("Motorlab", "Generate File"))
        self.DataExplorerGroup.setTitle(_translate("Motorlab", "Data Explorer"))
        self.DataExplorer.setHtml(_translate("Motorlab", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">MotorLab v2.0</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.PlotToolsGroup.setTitle(_translate("Motorlab", "Plot Tools"))
        self.DataPlotGroup.setTitle(_translate("Motorlab", "Data Plot"))
        self.PlotDataButton.setText(_translate("Motorlab", "Plot Data"))
        self.ModelPlotGroup.setTitle(_translate("Motorlab", "Model Plot"))
        self.StepModelButton.setText(_translate("Motorlab", "Step Model"))
        self.BodeModelButton.setText(_translate("Motorlab", "Bode Model"))
        self.ComparisonGroup.setTitle(_translate("Motorlab", "Comparison Plot"))
        self.DataModelButton.setText(_translate("Motorlab", " Data + Model"))
        self.FitDataCheckBox.setText(_translate("Motorlab", "Fit Data"))
        self.PlotAutoFormatCheckBox.setText(_translate("Motorlab", "Plot AutoFormat"))
        self.PlotAllDataCheckBox.setText(_translate("Motorlab", "Plot All Data"))
        self.checkBox.setText(_translate("Motorlab", "Experiment"))
        self.ModelGroup.setTitle(_translate("Motorlab", "OL Model"))
        self.TransferFunctionGroup.setTitle(_translate("Motorlab", "Transfer Function"))
        self.Numerator.setText(_translate("Motorlab", "1,2"))
        self.Denominator.setText(_translate("Motorlab", "1,0.7,3"))
        self.NumeratorLabel.setText(_translate("Motorlab", "Numerator"))
        self.DenominatorLabel.setText(_translate("Motorlab", "Denominator"))
        self.InputGroup.setTitle(_translate("Motorlab", "Input"))
        self.WaveTypeGroup.setTitle(_translate("Motorlab", "Wave Type"))
        self.WaveTypeComboBox.setItemText(0, _translate("Motorlab", "Sine"))
        self.WaveTypeComboBox.setItemText(1, _translate("Motorlab", "Square"))
        self.WaveTypeComboBox.setItemText(2, _translate("Motorlab", "Triangle"))
        self.WaveTypeComboBox.setItemText(3, _translate("Motorlab", "Trapezoidal"))
        self.WaveParametersGroup.setTitle(_translate("Motorlab", "Wave Parameters"))
        self.MagnitudeLabel.setText(_translate("Motorlab", "Magnitude"))
        self.Magnitude.setText(_translate("Motorlab", "1"))
        self.FrequencyLabel.setText(_translate("Motorlab", "Frequency (Hz)"))
        self.Frequency.setText(_translate("Motorlab", "1"))
        self.ManualCommandGroup.setTitle(_translate("Motorlab", "Manual Command"))
        self.JogDownButton.setText(_translate("Motorlab", "-"))
        self.JogUpButton.setText(_translate("Motorlab", "+"))
        self.CommandLabel.setText(_translate("Motorlab", "Command"))
        self.Command.setText(_translate("Motorlab", "0"))
        self.StepSizeLabel.setText(_translate("Motorlab", "Step Size"))
        self.StepSize.setText(_translate("Motorlab", "1.0"))
        self.RunWaveAutoSaveButton.setText(_translate("Motorlab", "Run Wave AutoSave"))
        self.RunWaveContinuousButton.setText(_translate("Motorlab", "Run Wave Continuous"))
        self.DisplayGroup.setTitle(_translate("Motorlab", "Display"))
        self.ResetEncodersButton.setText(_translate("Motorlab", "Reset Encoders"))
        self.PositionLabel.setText(_translate("Motorlab", "Position (Deg)"))
        self.Speed.setText(_translate("Motorlab", "0"))
        self.Position.setText(_translate("Motorlab", "0"))
        self.SpeedLabel.setText(_translate("Motorlab", "Speed (RPM)"))
        self.ModelGroup_2.setTitle(_translate("Motorlab", "CL Model"))
        self.TransferFunctionGroup_2.setTitle(_translate("Motorlab", "Transfer Function"))
        self.NumeratorCL.setText(_translate("Motorlab", "1,2"))
        self.DenominatorCL.setText(_translate("Motorlab", "1,0.7,3"))
        self.NumeratorLabel2.setText(_translate("Motorlab", "Numerator"))
        self.DenominatorLabel2.setText(_translate("Motorlab", "Denominator"))
        self.OpenFlashDir.setText(_translate("Motorlab", "..."))
        self.FlashMotorLabDir.setText(_translate("Motorlab", "Flash .bat to Motorlab"))
        self.COMPortComboBox.setItemText(0, _translate("Motorlab", "COM1"))
        self.RefreshComButton.setText(_translate("Motorlab", "Refresh"))
        self.ConnectComButton.setText(_translate("Motorlab", "Connect"))
        self.FlashButton.setText(_translate("Motorlab", "Flash"))
        self.label.setText(_translate("Motorlab", "Connect to the Motorlab"))
        self.ExperimentalArea.setTitle(_translate("Motorlab", "Experimental Area"))
        self.Terminal.setPlainText(_translate("Motorlab", "import numpy\n"
"import control as ctrl\n"
"from scipy import signal\n"
"import matplotlib.pyplot as plt\n"
"\n"
"kt = 0.05            #N*m/A\n"
"J = 1.29*10**-5        #kg*m^2 or N*m*s^2/rad\n"
"b = 3*10**-5        #n*m*s/rad\n"
"kdr = 180/numpy.pi        #deg/rad\n"
"\n"
"den = [J, b, 0]\n"
"num = [kt*kdr]\n"
"\n"
"Gm =ctrl.tf(num, den)\n"
"\n"
"#gain\n"
"kp = 0.0001\n"
"\n"
"#open loop TF\n"
"G = kp*Gm\n"
"\n"
"#closed loop TF\n"
"T1 = ctrl.feedback(G,1)\n"
"\n"
"#get data for step input\n"
"resp1, time1, = ctrl.matlab.step(T1)\n"
"\n"
"#get DC gain line\n"
"get_last_value = resp1[-1]\n"
"dcgain1 = [get_last_value]*len(time1)\n"
"\n"
"#new gain, get all info\n"
"kp = 0.001\n"
"G = kp*Gm\n"
"T2 = ctrl.feedback(G,1)\n"
"resp2, time2, = ctrl.matlab.step(T2)\n"
"get_last_value = resp2[-1]\n"
"dcgain2 = [get_last_value]*len(time2)\n"
"\n"
"#new gain, get all info\n"
"kp = 0.01\n"
"G = kp*Gm\n"
"T3 = ctrl.feedback(G,1)\n"
"resp3, time3, = ctrl.matlab.step(T3)\n"
"get_last_value = resp3[-1]\n"
"dcgain3 = [get_last_value]*len(time3)\n"
"\n"
"#plot step response\n"
"plt.figure(1)     \n"
"plt.ion()\n"
"plt.rc(\'font\', family=\'serif\')\n"
"plt.rc(\'xtick\', labelsize=\'x-small\')\n"
"plt.rc(\'ytick\', labelsize=\'x-small\')\n"
"plt.plot(time1,resp1,\'dodgerblue\',time1,dcgain1,\'k:\',time2,resp2,\'green\',time2,dcgain2,\'k:\',time3,resp3,\'red\',time3,dcgain3,\'k:\')\n"
"plt.xlabel(\'Time (seconds)\')\n"
"plt.ylabel(\'Amplitude\')\n"
"plt.title(\'Theoretical Step Response\')\n"
"plt.show()\n"
"\n"
"#get data for bode plot\n"
"w, mag, phase = signal.bode((num,den))        \n"
"constant_line_gain = [0]*w\n"
"\n"
"#plot bode\n"
"plt.ion()\n"
"plt.rc(\'font\', family=\'serif\')\n"
"plt.rc(\'xtick\', labelsize=\'x-small\')\n"
"plt.rc(\'ytick\', labelsize=\'x-small\')    \n"
"f, axarr = plt.subplots(2, sharex=True)\n"
"\n"
"plt.subplot(211)\n"
"plt.semilogx(w,mag,\'dodgerblue\',label=\'OL TF\')\n"
"plt.legend(loc=\'upper right\')\n"
"plt.title(\'Theoretical Bode Diagram\')\n"
"plt.ylabel(\'Magnitude (dB)\')\n"
"plt.grid(True, which=\"both\")\n"
"\n"
"plt.subplot(212)\n"
"plt.semilogx(w, phase,\'dodgerblue\',label=\'Phase\')  \n"
"plt.ylabel(\'Phase (Deg)\')\n"
"plt.xlabel(\'Frequency (rad/s)\')\n"
"plt.grid(True,which=\"both\")\n"
"plt.show()"))
        self.RunButton.setText(_translate("Motorlab", "Run"))

